"""empty message

Revision ID: 3f9d64d8c005
Revises: 
Create Date: 2016-12-13 16:16:18.130093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9d64d8c005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('changelog_url', sa.String(), nullable=True),
    sa.Column('package_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('changelog')
    # ### end Alembic commands ###
